version: 2.22.1.{build}
configuration: Release
platform: x86
clone_depth: 1

environment:
  SignPathToken:
    secure: xaUj8cwvyB4tT2BPVKxdaa02eRC1GK6EaGknYDshwVr6UfG+wv6/txF+o86/LEF9
    
before_build:
- cmd: >-
    choco install windows-adk

    git submodule update --init

    nuget restore

    cmake.exe -G "Visual Studio 16 2019" -T v141_xp,host=x86 -A Win32 .\protobuf\cmake -Dprotobuf_BUILD_TESTS=OFF -B build\protobuf

    cmake.exe --build build\protobuf --config Release

    cmake.exe -G "Visual Studio 16 2019" -T v141_xp,host=x86 -A Win32 .\poco -DPOCO_STATIC=ON -DPOCO_MT=ON -B build\poco

    cmake.exe --build build\poco --config Release

build:
  project: PanelSwWixExtension.sln
  verbosity: normal

before_package:
- cmd: >-
    nuget pack PanelSwWixExtension\PanelSwWixExtension.nuspec -Version "%APPVEYOR_BUILD_VERSION%" -OutputDirectory build\nuget-out

- ps: >-
    Install-Module -Name SignPath

    Submit-SigningRequest -InputArtifactPath "build\nuget-out\PanelSwWixExtension.%APPVEYOR_BUILD_VERSION%.nupkg" -CIUserToken "{SignPathToken}" -OrganizationId "247d954d-acdc-41dd-8bd2-9ef69d21ca2b" -ProjectKey "PanelSwWixExtension" -SigningPolicyKey "release-signing" -OutputArtifactPath "build\nuget-out\PanelSwWixExtension.%APPVEYOR_BUILD_VERSION%.nupkg" -WaitForCompletion

artifacts:
  - path: 'build\nuget-out\PanelSwWixExtension.%APPVEYOR_BUILD_VERSION%.nupkg'
    name: PanelSwWixExtension.%APPVEYOR_BUILD_VERSION%.nupkg
