version: 2.24.1.{build}
skip_non_tags: true
configuration: Release
platform: x86
clone_depth: 1

init:
  # Set version number when tagged
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        $v = -join($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"), ".", $env:APPVEYOR_BUILD_NUMBER)
        Update-AppveyorBuild -Version $v
      }

clone_script:
- cmd: >-
    git clone -q --depth=1 -n --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
    
    cd %APPVEYOR_BUILD_FOLDER%
    
    git checkout -qf %APPVEYOR_REPO_COMMIT%
    
    git submodule update --init
    
before_build:
- cmd: >-
    choco install windows-adk

    nuget restore

    cmake.exe -G "Visual Studio 16 2019" -T v141_xp,host=x86 -A Win32 .\protobuf\cmake -Dprotobuf_BUILD_TESTS=OFF -B build\protobuf

    cmake.exe --build build\protobuf --config Release

    cmake.exe -G "Visual Studio 16 2019" -T v141_xp,host=x86 -A Win32 .\poco -DPOCO_STATIC=ON -DPOCO_MT=ON -B build\poco

    cmake.exe --build build\poco --config Release

build:
  project: PanelSwWixExtension.sln
  verbosity: normal

before_package:
- cmd: >-
    nuget pack PanelSwWixExtension\PanelSwWixExtension.nuspec -Version "%APPVEYOR_BUILD_VERSION%" -OutputDirectory build\nuget-out

artifacts:
  - path: 'build\nuget-out\PanelSwWixExtension.%APPVEYOR_BUILD_VERSION%.nupkg'
    name: PanelSwWixExtension.%APPVEYOR_BUILD_VERSION%.nupkg
