name: PanelSwWixExtension
on:
  push:
    tags:
      - v*
  workflow_dispatch:
env:
  CUSTOM_WIX_VERSION: '3.12.0-c105'
jobs:
  PanelSwWixExtension-Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: microsoft/setup-msbuild@v1.0.2          

      - name: Prepare for build
        run: |
          choco install windows-adk
          nuget restore
          cmake.exe -G "Visual Studio 16 2019" -T v141_xp,host=x86 -A Win32 .\protobuf\cmake -Dprotobuf_BUILD_TESTS=OFF -B build\protobuf
          cmake.exe --build build\protobuf --config Release
          cmake.exe -G "Visual Studio 16 2019" -T v141_xp,host=x86 -A Win32 .\poco -DPOCO_STATIC=ON -DPOCO_MT=ON -B build\poco
          cmake.exe --build build\poco --config Release

      - name: Build for default WiX
        run: msbuild PanelSwWixExtension.sln -p:Configuration=Release -p:Platform=x86 -p:NugetDir=""

      - name: Clean
        run: |
          Remove-Item "build\bin" -Force -Recurse
          Remove-Item "build\obj" -Force -Recurse
          Remove-Item "build\lib" -Force -Recurse

      - name: Update nuspec dependency for custom WiX build
        run: |
          $xmlDoc = New-Object System.Xml.XmlDocument
          $file = [System.IO.Path]::Combine($env:GITHUB_WORKSPACE, "PanelSwWixExtension", "PanelSwWixExtension-psw-wix.nuspec")
          [xml]$xmlDoc = Get-Content $file
          $node = $xmlDoc.SelectSingleNode('//*[local-name(.)="dependency" and ./@id="PanelSW.Custom.WiX"]/@version')
          $node.Value = $env:CUSTOM_WIX_VERSION
          $xmlDoc.Save($file)

          git diff -w

      - name: Build for custom WiX
        run: |          
          nuget install PanelSW.Custom.WiX -version $env:CUSTOM_WIX_VERSION
          msbuild PanelSwWixExtension.sln -p:Configuration=Release -p:Platform=x86 -p:NugetDir="" -p:NugetPrereleaseVersion=-psw-wix -p:WixToolPath="$env:GITHUB_WORKSPACE\PanelSW.Custom.WiX.$env:CUSTOM_WIX_VERSION\tools\bin\" -p:WixSdkPath="$env:GITHUB_WORKSPACE\PanelSW.Custom.WiX.$env:CUSTOM_WIX_VERSION\tools\sdk\" -p:WixTargetsPath="$env:GITHUB_WORKSPACE\PanelSW.Custom.WiX.$env:CUSTOM_WIX_VERSION\tools\bin\Wix.targets" -p:WixCATargetsPath="$env:GITHUB_WORKSPACE\PanelSW.Custom.WiX.$env:CUSTOM_WIX_VERSION\tools\sdk\Wix.CA.targets" -p:WixNativeCATargetsPath="$env:GITHUB_WORKSPACE\PanelSW.Custom.WiX.$env:CUSTOM_WIX_VERSION\tools\sdk\Wix.NativeCA.targets" -p:WixTasksPath="$env:GITHUB_WORKSPACE\PanelSW.Custom.WiX.$env:CUSTOM_WIX_VERSION\tools\bin\wixtasks.dll" -p:WixInstallPath="$env:GITHUB_WORKSPACE\PanelSW.Custom.WiX.$env:CUSTOM_WIX_VERSION\tools\bin\" -p:WixExtDir="$env:GITHUB_WORKSPACE\PanelSW.Custom.WiX.$env:CUSTOM_WIX_VERSION\tools\bin\" -p:LuxTargetsPath="$env:GITHUB_WORKSPACE\PanelSW.Custom.WiX.$env:CUSTOM_WIX_VERSION\tools\bin\lux.targets"

      - uses: actions/upload-artifact@v2
        with:
          name: nuget
          path: build\nuget-out\*.nupkg