name: PanelSwWixExtension-WiX4
on:
  workflow_dispatch:
    inputs:
      publish_nuget:
        description: 'Publish nuget package?'
        required: true
        default: false
        type: boolean

env:
  NUGET_PRERELEASE_VERSION: '-rc.4'

jobs:
  PanelSwWixExtension-Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          submodules: 'true'
      - uses: microsoft/setup-msbuild@v1

      - name: Resolve build version
        run: |
          $xmlDoc = New-Object System.Xml.XmlDocument
          $file = [System.IO.Path]::Combine("${{ github.workspace }}", "TidyBuild.custom.props")
          [xml]$xmlDoc = Get-Content $file
          $node = $xmlDoc.SelectSingleNode('//*[local-name(.)="FullVersion"]')
          Add-Content -Path ${{ github.env }} -Value ("FULL_VERSION=" + $node.InnerText + ".${{ github.run_number }}")

      - name: Prepare for build
        run: |
          choco install windows-adk
          nuget restore
          cmake.exe -G "Visual Studio 17 2022" -T v142,host=x86 -A Win32 .\protobuf -Dprotobuf_BUILD_TESTS=OFF -B build\protobuf
          cmake.exe --build build\protobuf --config Release
          cmake.exe -G "Visual Studio 17 2022" -T v142,host=x86 -A Win32 .\poco -DPOCO_STATIC=ON -DPOCO_MT=ON -B build\poco
          cmake.exe --build build\poco --config Release

      - name: Build PanelSwWixExtension for default WiX
        run: msbuild PanelSwWixExtension.sln -p:Configuration=Release -p:Platform=x86 -p:NugetDir="" -p:FullVersion=${{ env.FULL_VERSION }} -p:NugetPrereleaseVersion=${{ env.NUGET_PRERELEASE_VERSION }}

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: nuget
          path: build\nuget-out\*.nupkg

      - name: Publish nuget packages to github and nuget.org
        if: ${{ github.event.inputs.publish_nuget == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_PAT }}
        run: |
          dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          dotnet nuget push build\nuget-out\PanelSwWixExtension4.${{ env.FULL_VERSION }}${{ env.NUGET_PRERELEASE_VERSION }}.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source github
          dotnet nuget push build\nuget-out\PanelSwWixExtension4.${{ env.FULL_VERSION }}${{ env.NUGET_PRERELEASE_VERSION }}.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json
          git tag wix4-v${{ env.FULL_VERSION }}
          git push --tags




