name: PanelSwWixExtension-WiX4
on:
  push:
    tags:
      - wix4-v*
  workflow_dispatch:
env:
  NUGET_PRERELEASE_VERSION: '-rc.1'
jobs:
  PanelSwWixExtension-Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: microsoft/setup-msbuild@v1.0.2          

      - name: Prepare for build
        run: |
          choco install windows-adk
          nuget restore
          cmake.exe -G "Visual Studio 17 2022" -T v142,host=x86 -A Win32 .\protobuf\cmake -Dprotobuf_BUILD_TESTS=OFF -B build\protobuf
          cmake.exe --build build\protobuf --config Release
          cmake.exe -G "Visual Studio 17 2022" -T v142,host=x86 -A Win32 .\poco -DPOCO_STATIC=ON -DPOCO_MT=ON -B build\poco
          cmake.exe --build build\poco --config Release

      - name: Build PanelSwWixExtension for default WiX
        run: msbuild PanelSwWixExtension.sln -p:Configuration=Release -p:Platform=x86 -p:NugetDir="" -p:NugetPrereleaseVersion=$env:NUGET_PRERELEASE_VERSION

      - uses: actions/upload-artifact@v2
        with:
          name: nuget
          path: build\nuget-out\*.nupkg

      - name: Extract tag name
        uses: actions-ecosystem/action-regex-match@v2.0.2
        id: tagName
        if: startsWith(github.ref, 'refs/tags/wix4-v')
        with:
          text: ${{ github.ref }}
          regex: '^refs\/tags\/wix4-v(.*)$'

      - name: Publish nuget packages to github and nuget.org
        if: startsWith(github.ref, 'refs/tags/wix4-v')
        run: |
          dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          dotnet nuget push build\nuget-out\PanelSwWixExtension4.${{ steps.tagName.outputs.group1 }}.${{ github.run_number }}$env:NUGET_PRERELEASE_VERSION.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source github
          dotnet nuget push build\nuget-out\PanelSwWixExtension4.${{ steps.tagName.outputs.group1 }}.${{ github.run_number }}$env:NUGET_PRERELEASE_VERSION.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json




